### ISSUE TITLE
Dades de les ABS

### ISSUE THREAD

**Issue by RamiroMF** [ibesora/covid-19-data#1]
Aquí (http://salutweb.gencat.cat/ca/el_departament/estadistiques_sanitaries/cartografia/ ) pots trobar un zip  amb les ABS per si vols afegir-les a les dades '2020-03-28-areesBasiques.json' i '2020-03-28-areesBasiques.csv'.

**Comment by RamiroMF** [comment]
He fet un join ràpid. Si t'interesa puc fer un pull request i afegeixo un parell d'scripts per fer-ho de forma automàtica.
[areesBasiquesgeo.zip](https://github.com/ibesora/covid-19-data/files/4397685/areesBasiquesgeo.zip)

**Comment by ibesora** [comment]
Ep! Si fas un PR perfecte!

**Comment by ibesora** [comment]
Ep, a partir del geojson que em vas passar he modificat l'script pq també generi un geojson amb les dades que toquen. Merci!

**Comment by RamiroMF** [comment]
Bones! Just t'anava a passar l'script per fer el merge. Pero si ja ho tens guay. No em deixa fer un PR així que te'l deixo aquí. 
[files_merger.zip](https://github.com/ibesora/covid-19-data/files/4398545/files_merger.zip)
