### ISSUE TITLE
NaN at PCRByAgeRange.csv

### ISSUE THREAD

**Issue by saludes** [ibesora/covid-19-data#2]
`2020-03-29-PCRByAgeRange.csv` has `NaN` at the bottom of it. Shouldn't it be 90, 100 ?

**Comment by ghost** [comment]
@saludes yes, you're right, 100 as max value is fine, but what happens with people oldest than 100 ?, are they out of range ?. The soluton is change the method `convertPCRByAgeFromResponse` to transform the X-Y range to expect X-Y and X +, that's the causant of the bug. i.e:

`const range = /\+$/i.test(e.C[0]) ? [e.C[0].split(' ')[0], e.C[0].split(' ')[0] + 10] : e.C[0].split("-")`.

Anyway, great job @ibesora .

**Comment by ibesora** [comment]
Thanks @saludes for pointing this out, they changed the way ranges were in the response (there was a 90 - 100 range during the first days).
Thanks @EdgarAyllon for the solution!
